# -*- coding: utf-8 -*-
"""tesoreria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rM_Z6ZmGMMVbqka_grPnmFDEAdLR2Atb
"""

import streamlit as st
import sqlite3
import pandas as pd
from datetime import date

st.set_page_config(
    page_title="Tesorería AA",
    page_icon="💰",
    layout="wide"
)

#====================================================
# BASE DE DATOS
#====================================================

conn = sqlite3.connect("tesoreria.db", check_same_thread=False)
c = conn.cursor()

c.execute("""
CREATE TABLE IF NOT EXISTS ingresos(
id INTEGER PRIMARY KEY AUTOINCREMENT,
fecha TEXT,
concepto TEXT,
monto REAL,
observaciones TEXT
)
""")

c.execute("""
CREATE TABLE IF NOT EXISTS egresos(
id INTEGER PRIMARY KEY AUTOINCREMENT,
fecha TEXT,
categoria TEXT,
monto REAL,
observaciones TEXT
)
""")

conn.commit()

#====================================================
# TÍTULO
#====================================================

st.title("💰 Tesorería - Alcohólicos Anónimos")

tab1, tab2, tab3 = st.tabs(
[
"➕ Registrar ingreso",
"➖ Registrar egreso",
"📊 Resumen"
])

#====================================================
# INGRESOS
#====================================================

with tab1:

    st.subheader("Registrar Sétimas")

    fecha = st.date_input(
        "Fecha",
        value=date.today(),
        key="ingreso_fecha"
    )

    monto = st.number_input(
        "Monto",
        min_value=0.0,
        step=10.0,
        key="ingreso_monto"
    )

    obs = st.text_area(
        "Observaciones",
        key="ingreso_obs"
    )

    if st.button("Guardar ingreso"):

        c.execute("""
        INSERT INTO ingresos(fecha,concepto,monto,observaciones)
        VALUES(?,?,?,?)
        """,
        (
        fecha.strftime("%Y-%m-%d"),
        "Sétimas",
        monto,
        obs
        ))

        conn.commit()

        st.success("Ingreso guardado correctamente.")

#====================================================
# EGRESOS
#====================================================

with tab2:

    st.subheader("Registrar egreso")

    fecha = st.date_input(
        "Fecha",
        value=date.today(),
        key="egreso_fecha"
    )

    categoria = st.selectbox(
        "Categoría",
        [
        "Jabón",
        "Fabuloso",
        "Cloro",
        "Azúcar",
        "Nescafé",
        "Té",
        "Distrito",
        "Otros"
        ]
    )

    monto = st.number_input(
        "Monto",
        min_value=0.0,
        step=10.0,
        key="egreso_monto"
    )

    obs = st.text_area(
        "Observaciones",
        key="egreso_obs"
    )

    if st.button("Guardar egreso"):

        c.execute("""
        INSERT INTO egresos(fecha,categoria,monto,observaciones)
        VALUES(?,?,?,?)
        """,
        (
        fecha.strftime("%Y-%m-%d"),
        categoria,
        monto,
        obs
        ))

        conn.commit()

        st.success("Egreso guardado correctamente.")

#====================================================
# RESUMEN
#====================================================

with tab3:

    ingresos = pd.read_sql(
        "SELECT * FROM ingresos",
        conn
    )

    egresos = pd.read_sql(
        "SELECT * FROM egresos",
        conn
    )

    total_ingresos = ingresos["monto"].sum() if len(ingresos)>0 else 0

    total_egresos = egresos["monto"].sum() if len(egresos)>0 else 0

    saldo = total_ingresos-total_egresos

    c1,c2,c3 = st.columns(3)

    c1.metric(
        "Ingresos",
        f"${total_ingresos:,.2f}"
    )

    c2.metric(
        "Egresos",
        f"${total_egresos:,.2f}"
    )

    c3.metric(
        "Saldo",
        f"${saldo:,.2f}"
    )

    st.divider()

    st.subheader("Ingresos")

    st.dataframe(
        ingresos,
        use_container_width=True
    )

    st.subheader("Egresos")

    st.dataframe(
        egresos,
        use_container_width=True
    )
#====================================================
# MODIFICAR REGISTROS
#====================================================

st.divider()

st.subheader("✏️ Modificar registro")


tipo_modificar = st.selectbox(
    "Tipo de registro",
    ["Ingreso", "Egreso"]
)


if tipo_modificar == "Ingreso":

    datos = pd.read_sql(
        "SELECT * FROM ingresos",
        conn
    )

    if len(datos) > 0:

        id_ingreso = st.selectbox(
            "Seleccione ID del ingreso",
            datos["id"]
        )

        registro = datos[
            datos["id"] == id_ingreso
        ].iloc[0]


        nueva_fecha = st.date_input(
            "Fecha",
            value=pd.to_datetime(
                registro["fecha"]
            ),
            key="mod_fecha_ing"
        )


        nuevo_monto = st.number_input(
            "Monto",
            value=float(registro["monto"]),
            key="mod_monto_ing"
        )


        nueva_obs = st.text_area(
            "Observaciones",
            value=registro["observaciones"],
            key="mod_obs_ing"
        )


        if st.button("Actualizar ingreso"):

            c.execute("""
            UPDATE ingresos
            SET fecha=?,
                monto=?,
                observaciones=?
            WHERE id=?
            """,
            (
            nueva_fecha.strftime("%Y-%m-%d"),
            nuevo_monto,
            nueva_obs,
            id_ingreso
            ))

            conn.commit()

            st.success(
                "Ingreso actualizado correctamente"
            )

            st.rerun()

    else:
        st.info("No existen ingresos registrados")


else:

    datos = pd.read_sql(
        "SELECT * FROM egresos",
        conn
    )


    if len(datos) > 0:

        id_egreso = st.selectbox(
            "Seleccione ID del egreso",
            datos["id"]
        )


        registro = datos[
            datos["id"] == id_egreso
        ].iloc[0]


        nueva_fecha = st.date_input(
            "Fecha",
            value=pd.to_datetime(
                registro["fecha"]
            ),
            key="mod_fecha_egr"
        )


        nueva_categoria = st.selectbox(
            "Categoría",
            [
            "Jabón",
            "Fabuloso",
            "Cloro",
            "Azúcar",
            "Nescafé",
            "Té",
            "Distrito",
            "Otros"
            ],
            index=[
            "Jabón",
            "Fabuloso",
            "Cloro",
            "Azúcar",
            "Nescafé",
            "Té",
            "Distrito",
            "Otros"
            ].index(registro["categoria"])
        )


        nuevo_monto = st.number_input(
            "Monto",
            value=float(registro["monto"]),
            key="mod_monto_egr"
        )


        nueva_obs = st.text_area(
            "Observaciones",
            value=registro["observaciones"],
            key="mod_obs_egr"
        )


        if st.button("Actualizar egreso"):

            c.execute("""
            UPDATE egresos
            SET fecha=?,
                categoria=?,
                monto=?,
                observaciones=?
            WHERE id=?
            """,
            (
            nueva_fecha.strftime("%Y-%m-%d"),
            nueva_categoria,
            nuevo_monto,
            nueva_obs,
            id_egreso
            ))


            conn.commit()

            st.success(
                "Egreso actualizado correctamente"
            )

            st.rerun()

    else:
        st.info("No existen egresos registrados")

    excel_ing = ingresos.to_csv(index=False).encode("utf-8")

    st.download_button(
        "Descargar ingresos CSV",
        excel_ing,
        "ingresos.csv",
        "text/csv"
    )

    excel_egr = egresos.to_csv(index=False).encode("utf-8")

    st.download_button(
        "Descargar egresos CSV",
        excel_egr,
        "egresos.csv",
        "text/csv"
    )
#====================================================
# RESTABLECER DATOS
#====================================================

    st.divider()

    st.subheader("🗑️ Restablecer tesorería")

    st.warning(
        "Esta opción eliminará todos los ingresos y egresos registrados."
    )

    confirmar = st.checkbox(
        "Confirmo que deseo eliminar todos los registros"
    )


    if confirmar:

        if st.button("Restablecer datos"):

            c.execute(
                "DELETE FROM ingresos"
            )

            c.execute(
                "DELETE FROM egresos"
            )

            conn.commit()

            st.success(
                "La tesorería fue restablecida correctamente."
            )

            st.rerun()
conn.close()
